pretrained_model: null
context_len: 512


config_args:
  base_model_name: facebook/opt-125m
  vocab_size: -1
  dropout: 0.0
  attention_dropout: 0.0
  layerdrop: 0.0
  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 1
  use_cache: false
  attn_implementation: null
  trust_remote_code: null
  use_safetensors: null
  torch_dtype: null
